webdetails/ccc

package-res/ccc/plugin/point/point-plot-panel.js
package-res/ccc/plugin/scatter/scatter-plot-panel.js
package-res/lib/tipsy.js

[CDF-422]: CCC - Tooltip moves when hovering over a chart dot

---

build-res/r.js-configs/cdo.build.js
cdo-bundle-files.js
cdo-bundle-files.txt
doc/model/format/formatProvider.xml
doc/model/format/numberFormat.xml
doc/model/format/numberFormatStyle.xml
package-res/cdo/format/format-language.js
package-res/cdo/format/formatProvider.js
package-res/cdo/format/number-format.js
package-res/cdo/format/number-formatStyle.js
package-res/def/type/fields.js
test/cdo/format/format-language-spec.js

[CDF-458]: Build capability to format numbers into CDF

---

package-res/ccc/core/base/chart/chart.js
package-res/cdo/format/format-language.js
package-res/cdo/format/number-format.js
test/cdo/format/format-language-spec.js
test/cdo/format/formatProvider-spec.js
test/cdo/format/number-format-spec.js

[CDF-458]: more unit tests and style review

---

doc/model/format/formatProvider.xml
package-res/cdo/format/format-language.js
package-res/cdo/format/formatProvider.js
test/cdo/format/format-language-spec.js
test/cdo/format/formatProvider-spec.js

[CDF-458]: Added fallback logic to language provider

---

package-res/cdo/data/data.js
test/cdo/data-spec.js

[CDF-480]: CCC - Typo _dimensionsLIst can cause memory leak

---

package-res/cdo/format/number-format.js

[CDF-458] New mask 'A' and 'C' to format numbers with abbreviations and currency

---

test/cdo/format/number-format-spec.js

[CDF-358]: fix broken test because now 'A' is also a special character

---

doc/model/charts/common.xml
package-res/ccc/core/base/context.js
package-res/ccc/core/base/panel/panel/panel.js

[CDF-498] - CCC - multiple selection - CTRL + click does not work on Mac

---

package-res/ccc/core/base/axis/axis.js

[CDF-496] - CCC - Function declaration inside If does not work consistently across browsers

---

package-res/ccc/core/base/panel/panel/panel.js
package-res/lib/protovis.js

[CDF-497] - CCC - Pointing radius Infinity is a bit too infinite

---

package-res/ccc/core/cartesian/axis/abstract-cart-axis-panel.js

[CDF-477] CCC - Cartesian axis fixed size is not respected when there's no axis data

---

package-res/ccc/core/base/prologue.js

[CDF-482] - CCC - Tipsy - Log level no longer synchronized with that of CCC

---

doc/model/charts/basic.xml
package-res/ccc/core/base/chart/chart.js
package-res/ccc/core/base/panel/panel/panel.js

[CDF-478] - CCC - Add a renderedCallback

---

package-res/ccc/core/base/panel/legend/legend-panel.js
package-res/ccc/core/base/panel/legend/legendSymbolRenderer.js

[CDF-493] - CCC - Disabled legend item label shows "text" mouse cursor

---

package-res/lib/tipsy.js

[CDF-481] - CCC - Tipsy uses function from undeclared dependency def.js

---

doc/model/axes/axis-color.xml

[CDF-450] - CCC - Sunburst - Undocumented option "SliceBrightnessFactor"

---

package-res/ccc/core/base/sign/value-label-sign.js
package-res/ccc/plugin/abstract-bar/abstract-bar-plot-panel.js

* Hiding null bars, by default.

[CDF-412] - CCC - Bar plot - Null value label is visible

---

package-res/ccc/plugin/bullet/bullet-chart.js

* Oops... wrong Bullet chart default value for dataTypeCheckingMode...

[CDF-443] - CCC - Sunburst - Misbehavior of colorRole and colorMode

---

doc/model/axes/axis-cartesian.xml

[CDF-504] CCC - expose baseAxisFont for CCC Charts on CDE's advanced properties

---

ivysettings.xml

Built fine on nightly with new ivysettings.xml file

[CLEANUP] update ivysettings file

---

package-res/ccc/core/base/mark.js

[CLEANUP] Dangling character in odd position.

---

build-res/r.js-configs/def.build.js
build-res/r.js-configs/pvc.build.js
ccc-bundle-files.txt
def-bundle-files.txt
package-res/ccc/core/base/chart/chart.js
package-res/ccc/core/base/spec.js
package-res/def/EventSource.js
test/def/EventSource-spec.js

[CDF-565] - CCC - Events

---

package-res/ccc/core/cartesian/cart-plot-panel.js
package-res/ccc/plugin/abstract-bar/abstract-bar-plot-panel.js

[CDE-559] - CCC - Bar Chart - Bars overflow when !stacked, !orthoAxisOriginIsZero and only positive values

---

build.properties

[ENGOPS-1320] Wrong version fix

---

package-res/ccc/core/base/optionsMgr.js
package-res/cdo/oper/linear-interp-oper.js
package-res/lib/protovis.js

[CLEANUP] Unintended global variables.

---

package-res/ccc/core/base/panel/legend/scene/legend-group-scene.js

* This fix avoids the errors but does not fix the root cause (whichever it is).

[CDF-620] - Bug when hovering over a legend marker with plot2 after hiding a series

---

package-res/ccc/core/base/panel/legend/scene/legend-item-scene.js

@pentaho/millenniumfalcon please review.

[BACKLOG-9052] Fix no tooltip in legend not showing when items are not "executable"

---

package-res/lib/protovis.js

Had forgotten to review protovis changes...

[CDF-603] Removing unwanted global variables from Protovis.

---

package-res/ccc/core/base/panel/panel/panel.js

Caused the initial size of a hidden legend panel to still be considered...

[CDF-603] Small regression, probably caused by incorrect merging procedure.

---

doc/model/data/slidingWindow.xml

[CDF-603] Fix properties documentation and CDE output.

---

doc/model/axes/axis-cartesian-discrete.xml
doc/model/axes/axis-cartesian.xml
doc/model/varia/_varia.xml
doc/model/varia/atoms/axisLabelRotationDirection.xml
doc/model/varia/atoms/axisOverlappedLabelsMode.xml
package-res/ccc/core/base/panel/dockingGrid-panel.js
package-res/ccc/core/base/panel/panel/panel.js
package-res/ccc/core/base/value/enums.js
package-res/ccc/core/cartesian/axis/abstract-cart-axis-panel.js
package-res/ccc/core/cartesian/axis/cart-axis.js
test/ccc/core/cartesian/axis/abstract-cart-axis-panel-spec.js

@pentaho/millenniumfalcon, please review.
@dcleao, I had conflits and needed to rebase, so you'll need to also rebase your branch.
@jheck123, you just need to comment on commit 378c778.

[BACKLOG-9117] Automatic axis label's non-overlapping angle

---

package-res/ccc/core/base/panel/dockingGrid-panel.js
package-res/ccc/core/base/panel/panel/panel.js
package-res/ccc/core/base/value/sides.js
package-res/ccc/core/cartesian/axis/cart-axis.js
package-res/ccc/core/cartesian/cart-chart.js
package-res/ccc/core/cartesian/cart-plot-panel.js
test/ccc/core/base/chart/chart-spec.js
test/ccc/core/base/panel/dockingGrid-panel-spec.js
test/data-1.js

@pamval, @davidmsantos90, @nantunes @graimundo @carlosrusso @marcovala please review.

[CDF-912] CCC - Axis tick label overflows - layout fails to take axis offset into account

---

package-res/ccc/core/base/panel/dockingGrid-panel.js
package-res/ccc/core/base/panel/panel/panel.js
package-res/ccc/core/base/value/sides.js
package-res/ccc/core/cartesian/axis/abstract-cart-axis-panel.js
package-res/ccc/core/cartesian/axis/cart-axis.js
package-res/ccc/core/cartesian/cart-chart.js
package-res/ccc/core/cartesian/cart-plot-panel.js
test/ccc/core/base/chart/chart-spec.js
test/ccc/core/base/panel/dockingGrid-panel-spec.js
test/ccc/core/cartesian/axis/abstract-cart-axis-panel-spec.js
test/data-1.js
test/utils.js

Please do not merge before https://github.com/webdetails/ccc/pull/249, as this PR is based on that one.
@pamval @davidmsantos90 @nantunes @graimundo @carlosrusso @marcovala please review.

[CDF-913] CCC - Axis tick label overflows - ignores fixed or maximum axis sizes

---

package-res/ccc/core/cartesian/axis/abstract-cart-axis-panel.js
test/ccc/core/cartesian/axis/abstract-cart-axis-panel-spec.js

@pentaho/millenniumfalcon please review.

[BACKLOG-10514] Fixes relating time-series use

---

doc/model/panels/title.xml
package-res/ccc/core/base/chart/chart.js
package-res/ccc/core/base/chart/chart.panels.js
package-res/ccc/core/base/multi/multiChart-panel.js
package-res/ccc/core/base/panel/title/abstract-title-panel.js
package-res/ccc/core/cartesian/axis/cart-axis.js
package-res/ccc/core/cartesian/cart-chart.js

@nantunes @graimundo @marcovala @carlosrusso @davidmsantos90 please review.

[BACKLOG-11191] Add axis/chart/small-chart title visible options.

---

package-res/cdo/dimension.js

@nantunes @dcleao @carlosrusso please review

[BACKLOG-10865] Null values weren't keeping the formatted value if it was previously specified

---

package-res/ccc/core/cartesian/axis/cart-axis.js

@nantunes @dcleao @carlosrusso please review

[BACKLOG-15218] Don't force a minimum band size when multi chart is bound

---

doc/model/axes/axis-color.xml
doc/model/varia/atoms/sunburstColorMode.xml
package-res/ccc/plugin/sunburst/sun-color-axis.js
package-res/ccc/plugin/sunburst/sun-plot-panel.js
package-res/ccc/plugin/sunburst/sun-plot.js

@davidmsantos90, @carlosrusso, @nantunes please review.
Merge with: https://github.com/webdetails/cde/pull/776 and https://github.com/pentaho/pentaho-platform-plugin-common-ui/pull/982

[BACKLOG-15020] New Sunburst color mode, `level`.

---

doc/kettle/configPropertyDefaultOverride.csv

- Added exception for baseAxisOverlappedLabelsMode and baseAxisLabelRotationDirection
@dcleao @afrjorge please review

[BACKLOG-14077]

---

doc/model/axes/axis-color.xml
package-res/ccc/core/base/sign/value-label-sign.js
package-res/ccc/plugin/sunburst/sun-color-axis.js
package-res/ccc/plugin/sunburst/sun-plot-panel.js
package-res/def/number.js
package-res/lib/protovis.js

@carlosrusso, @nantunes, @davidmsantos90, @graimundo please review.
See associated PRs:
1. https://github.com/webdetails/protovis/pull/30
2. https://github.com/webdetails/cde/pull/778
3. https://github.com/pentaho/pentaho-platform-plugin-common-ui/pull/994

[BACKLOG-15553] Sunburst color mode, levels by alpha-step.

---

package-res/ccc/core/base/sign/value-label-sign.js
package-res/lib/protovis.js

@carlosrusso, @nantunes, @davidmsantos90, @graimundo please review.
Depends on https://github.com/webdetails/protovis/pull/31.

[BACKLOG-15553] Fixed alphaBlending!

---

package-res/ccc/core/base/sign/dot-sign.js

@nantunes @dcleao @graimundo @carlosrusso please review

[BACKLOG15707] DET: Heat Grid doesn't render when we had a field to the "Size" drop zone

---

package-res/ccc/plugin/sunburst/sun-color-axis.js

@davidmsantos90, @carlosrusso, @graimundo, @nantunes please review.

[BACKLOG-14077] Fix bug.

---

doc/kettle/configPropertyDefaultOverride.csv

[BACKLOG-14077] - Removed default for useShapes

---

doc/kettle/configPropertyDefaultOverride.csv

[BACKLOG-14077] - Reverted changes to Selectable and Hoverable in CDE

---

package-res/ccc/core/cartesian/axis/abstract-cart-axis-panel.js

@graimundo, @carlosrusso, @davidmsantos90, @dcleao, @marcovala please review.

[BACKLOG-15937] Take plotSizeMin into account when calculating continuous axis ticks

---

package-res/cdo/dimension.js

[ANALYZER-3616]-Chart Labels show incorrect formatting when different rows have "Matching Values"

---

package-res/ccc/core/base/chart/chart.js
package-res/ccc/core/base/value/enums.js

[BACKLOG-17820] Disable lasso selection on vizualisations.

---

package-res/cdo/complex.js
package-res/cdo/datum.js

@webdetails/millenniumfalcon, @stanislau-strelchanka please review.
/cc @pamval

[CDF-976]  Fix regression.

---

package-res/cdo/complex.js
package-res/def/object.js

[BACKLOG-18740] In complex add null atoms if only defined at the root proto object

---

package-res/ccc/core/cartesian/axis/abstract-cart-axis-panel.js

@webdetails/millenniumfalcon please review

[BACKLOG-15967]  - Hiding root level labels to prevent selection

---

ccc.css
charts/bar.html
charts/boxplot.html
charts/bullet.html
charts/dot.html
charts/heatgrid.html
charts/line.html
charts/metricdot.html
charts/pie.html
charts/stackedarea.html
charts/stackedline.html
charts/sunburst.html
charts/treemap.html
charts/waterfall.html
css/main.css
css/master.css
files/protovis.html

Fixing fixed protocol in font urls

---

charts/lib/amd/require.config.js

Fixing require.config.js file.

---

package-res/cdo/complex.js
package-res/cdo/data/data.js
package-res/cdo/data/data.operations.js
package-res/cdo/meta/complexType.js
package-res/def/object.js

[BACKLOG-18740] Allow null values on where specification

---

charts/lib/amd/cdo.js
charts/lib/amd/def.js
charts/lib/amd/pvc.js
charts/lib/cdo.js
charts/lib/def.js
charts/lib/pvc.js

Updating CCC scripts.

---

ccc.css
index.html

Updated footer links

---

build-res/partials/license.js
build-res/subfloor-js.xml
build-res/subfloor-pkg.xml
build-res/subfloor.xml
ivysettings.xml
package-res/lib/protovis-compat.js
package-res/lib/protovis.js
site/root/js/master.js

WARNING!  FOR MERGE BY PROCESS ONLY PLEASE!

[ENGOPS-3544] change Pentaho to Hitachi Vantara and update copyright date

---

examples/data/q01-01.js
examples/pvcTestMeasureDiscrim.html
package-res/ccc/core/categorical/categ-plot.js
package-res/cdo/oper/linear-interp-oper.js
package-res/cdo/oper/zero-interp-oper.js
test/cdo/data-interp-linear-spec.js
test/cdo/data-interp-zero-spec.js

 [ANALYZER-3616] Two bugs, one on Trends and one on Interpolation

---

test/cdo/format/format-language-spec.js

[CLEANUP] Fixing unit tests to work with jasmine-core 2.9.0.

---

ccc-js/src/main/javascript/package-res/ccc/core/base/slidingWindow.js
ccc-js/src/main/javascript/package-res/ccc/core/cartesian/axis/cart-axis.js
ccc-js/src/main/javascript/package-res/lib/protovis.js
ccc-js/src/test/javascript/ccc/core/base/slidingWindow-spec.js
doc/model/axes/axis-cartesian-continuous.xml
examples/pvcTestRealTimeLineSlidingWindow.html

- Added new property - PreserveTickAlignment - to CCC in order to expose this feature to the user.
- Improved protovis - DateComponent -  to guarantee that the ticks keep the same regularity from one rendering to the next when tick alignement is active.
- Created new example file - pvcTestRealTimeLineSlidingWindow - that implements the use case of having a generated sliding window rendered by CCC line chart in a continuous way.
@dcleao please review.

[BACKLOG-22074] - CCC - reuse the horizontal axis ticks for continuity

---

doc/kettle/exportModelCDE.ktr

[BACKLOG-22074] - added renderMode and dataAdditiveMode properties

---

ccc-js/src/main/javascript/package-res/ccc/plugin/sunburst/sun-plot-panel.js

[BACKLOG-20943] Fix sunburst sort-order.

---

ccc-js/src/main/javascript/package-res/ccc/core/base/chart/chart.data.js
ccc-js/src/main/javascript/package-res/ccc/core/base/chart/chart.js
ccc-js/src/main/javascript/package-res/ccc/core/base/chart/chart.panels.js
ccc-js/src/main/javascript/package-res/ccc/core/base/multi/multiChart-options.js
ccc-js/src/main/javascript/package-res/ccc/core/base/multi/multiChart-panel.js
ccc-js/src/main/javascript/package-res/ccc/core/base/panel/panel/panel.js
ccc-js/src/main/javascript/package-res/ccc/core/base/value/enums.js

* Added the `page` value to the `multiChartOverflow` option.
* Added the `multiChartStart` option, to allow specifying the first small chart to include in the page.
* Added `BaseChart#getNextPageStartIndex` to allow querying for the existence of another page and at the value of `multiChartStart` option that should be specified.
* Added `BaseChart#renderPages` helper method to perform a full pagination render.

[BACKLOG-22643] Need all multi-charts from analyzer report to be exported to PDF

---

ccc-js/src/main/javascript/package-res/ccc/core/cartesian/axis/abstract-cart-axis-panel.js
ccc-js/src/main/javascript/package-res/ccc/plugin/point/point-plot-panel.js

[BACKLOG-24888] Area chart is not stacking the values

---

ccc-js/src/main/javascript/package-res/ccc/core/base/axis/axis.js
ccc-js/src/main/javascript/package-res/ccc/plugin/sunburst/sun-color-axis.js
ccc-js/src/main/javascript/package-res/ccc/plugin/treemap/treemap-color-axis.js
ccc-js/src/main/javascript/package-res/def/describe.js

[BACKLOG-25786] Distinct dates of millisecond precision are being grouped by the second (ii)

---

ccc-js/src/main/javascript/package-res/ccc/core/base/chart/chart.axes.js

[BACKLOG-26090] Layout issues in Scatter chart with only one dot with negative values.

---

site/root/ccc.css

[CLEANNUP] Updates CCC site for 8.2

---

ccc-js/src/main/javascript/package-res/ccc/core/base/plot/plot.js
ccc-js/src/main/javascript/package-res/ccc/core/categorical/categ-plot.js
ccc-js/src/main/javascript/package-res/ccc/plugin/abstract-metricxy/abstract-metricxy-chart.js
ccc-js/src/main/javascript/package-res/ccc/plugin/abstract-metricxy/abstract-metricxy-plot.js
ccc-js/src/main/javascript/package-res/ccc/plugin/point/point-chart.js
ccc-js/src/main/javascript/package-res/ccc/plugin/point/point-plot-panel.js
ccc-js/src/main/javascript/package-res/cdo/dimension.js
ccc-js/src/main/javascript/package-res/cdo/oper/linear-interp-oper.js
ccc-js/src/main/javascript/package-res/cdo/oper/zero-interp-oper.js
ccc-js/src/test/javascript/cdo/data-interp-linear-spec.js
ccc-js/src/test/javascript/cdo/data-interp-zero-spec.js
ccc-js/src/test/javascript/utils.js
examples/pvcTestSmallMultipleCharts.html

@pentaho/tattoine, @pentaho-lmartins, @RPAraujo please review.
/cc @webdetails/millenniumfalcon
Merge with: https://github.com/pentaho/pentaho-platform-plugin-common-ui/pull/1369.

[SP-4754] PAZ: In Scatter chart, adding a level to Multi-Chart drop z… 

---

ccc-js/src/main/javascript/package-res/ccc/core/base/chart/chart.activeScene.js
ccc-js/src/main/javascript/package-res/ccc/core/base/chart/chart.panels.js

[BACKLOG-27603] Charts Overlapping

---

ccc-js/src/main/javascript/package-res/ccc/core/base/colorScheme.js

- Make the code more robust, protecting against a null color.
Merge with: https://github.com/pentaho/pentaho-platform-plugin-common-ui/pull/1410.

[BACKLOG-28632] Error in Browser console when Trend Type is updated

---

ccc-js/src/main/javascript/package-res/ccc/plugin/point/point-chart.js

[ANALYZER-3937] Analyzer Line Graph Not Displaying All Data

---

ccc-js/src/main/javascript/package-res/ccc/plugin/point/point-chart.js

[SP-5595] Backport of ANALYZER-3937 - Analyzer Line Graph Not Displaying All Data

---

ccc-js/src/main/javascript/package-res/ccc/plugin/point/point-chart.js

[SP-5596] Backport of ANALYZER-3937 - Analyzer Line Graph Not Displaying All Data

---

ccc-js/src/main/javascript/package-res/ccc/core/base/panel/legend/legend-panel.js

[PPP-4587] Analyzer Data Source - Cross-Site Scripting

---

ccc-js/src/main/javascript/package-res/ccc/core/base/chart/chart.axes.js
ccc-js/src/main/javascript/package-res/ccc/core/cartesian/axis/cart-axis.js
ccc-js/src/main/javascript/package-res/cdo/atom.js

Specifically, the [commit "Remove constant NumberAtom#key getter"](https://github.com/webdetails/ccc/commit/7cb33a6245a2f2e35145189b6ef204fa5a8b6936) is most important.
This PR is part of a PR set: https://github.com/webdetails/cgg/pull/148.
@davidmsantos90, @afrjorge, @bennychow please review.
/cc @jcarneirohv

[ANALYZER-3942] Allow CCC to be loaded in the upgraded Rhino environment, for CGG printing

---

ccc-js/src/main/javascript/package-res/ccc/core/base/chart/chart.data.js
ccc-js/src/main/javascript/package-res/ccc/core/base/chart/chart.js

@andreramos89 
@bcostahitachivantara 
@smmribeiro

[ANALYZER-3593] - Analyzer Multi-Chart is hard-coded to show only 50 charts

---

ccc-js/src/main/javascript/package-res/ccc/core/base/chart/chart.data.js
ccc-js/src/main/javascript/package-res/ccc/core/base/chart/chart.js

Original PRs:
- https://github.com/webdetails/ccc/pull/387
@andreramos89
@bcostahitachivantara
@smmribeiro

[SP-6197] - Backport of ANALYZER-3593 - Analyzer Multi-Chart is hard-coded to show only 50 charts (9.3 Suite)
